apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
    environment: lab
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name:  nginx
spec:
  type:  NodePort
  ports:
  - name:  http
    nodePort: 30250
    port:  80
  selector:
    name:  nginx
